services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - todo-data:/app/data
    environment:
      - APP_ENV=dev  # dev | stg | prod
    env_file:
      - ./backend/.env

volumes:
  todo-data:
